id = "kome"
name = "Kome"
description = "Kome language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["mochiOS"]
repository = "https://github.com/mochiOS/komec"

[grammars.kome]
repository = "https://github.com/mochiOS/komec"
rev = "76f1be16f0856d2ce1e119a5845940c44f692d24"
path = "editors/zed/grammar"

[language_servers.kome-lsp]
name = "Kome Language Server"
language = "Kome"
