id = "kome"
name = "Kome"
description = "Kome language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["mochiOS"]
repository = "https://github.com/mochiOS/komec"

[grammars.kome]
repository = "https://github.com/mochiOS/komec"
rev = "aff3cb43b192c6db96f6a5cb9c7ee187a7d4db1f"
path = "editors/zed/grammar"

[language_servers.kome-lsp]
name = "Kome Language Server"
languages = ["Kome"]