[package]
name = "kome_aot"
version = "0.1.0"
edition.workspace = true

[dependencies]
cranelift.workspace = true
cranelift-frontend.workspace = true
cranelift-module.workspace = true
cranelift-native.workspace = true
cranelift-object.workspace = true
kome_ast.workspace = true
kome_codegen.workspace = true

[dev-dependencies]
kome_parser.workspace = true
