/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 70
#define ALIAS_COUNT 0
#define TOKEN_COUNT 61
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_AT = 3,
  anon_sym_DQUOTE = 4,
  sym_string_content = 5,
  sym_escape_sequence = 6,
  sym_percentage = 7,
  sym_number = 8,
  anon_sym_true = 9,
  anon_sym_false = 10,
  sym_null = 11,
  anon_sym_fn = 12,
  anon_sym_component = 13,
  anon_sym_enum = 14,
  anon_sym_extension = 15,
  anon_sym_recipe = 16,
  anon_sym_state = 17,
  anon_sym_let = 18,
  anon_sym_mut = 19,
  anon_sym_use = 20,
  anon_sym_if = 21,
  anon_sym_else = 22,
  anon_sym_while = 23,
  anon_sym_for = 24,
  anon_sym_in = 25,
  anon_sym_return = 26,
  anon_sym_break = 27,
  anon_sym_continue = 28,
  anon_sym_is = 29,
  anon_sym_DASH_GT = 30,
  anon_sym_EQ_GT = 31,
  anon_sym_PLUS_EQ = 32,
  anon_sym_DASH_EQ = 33,
  anon_sym_STAR_EQ = 34,
  anon_sym_SLASH_EQ = 35,
  anon_sym_EQ_EQ = 36,
  anon_sym_BANG_EQ = 37,
  anon_sym_LT_EQ = 38,
  anon_sym_GT_EQ = 39,
  anon_sym_AMP_AMP = 40,
  anon_sym_PIPE_PIPE = 41,
  anon_sym_EQ = 42,
  anon_sym_PLUS = 43,
  anon_sym_DASH = 44,
  anon_sym_STAR = 45,
  anon_sym_SLASH = 46,
  anon_sym_BANG = 47,
  anon_sym_LT = 48,
  anon_sym_GT = 49,
  anon_sym_QMARK = 50,
  anon_sym_PIPE = 51,
  anon_sym_LPAREN = 52,
  anon_sym_RPAREN = 53,
  anon_sym_LBRACE = 54,
  anon_sym_RBRACE = 55,
  anon_sym_LBRACK = 56,
  anon_sym_RBRACK = 57,
  anon_sym_COMMA = 58,
  anon_sym_DOT = 59,
  anon_sym_COLON = 60,
  sym_source_file = 61,
  sym_attribute = 62,
  sym_string = 63,
  sym_boolean = 64,
  sym_keyword = 65,
  sym_operator = 66,
  sym_punctuation = 67,
  aux_sym_source_file_repeat1 = 68,
  aux_sym_string_repeat1 = 69,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_AT] = "@",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_percentage] = "percentage",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_fn] = "fn",
  [anon_sym_component] = "component",
  [anon_sym_enum] = "enum",
  [anon_sym_extension] = "extension",
  [anon_sym_recipe] = "recipe",
  [anon_sym_state] = "state",
  [anon_sym_let] = "let",
  [anon_sym_mut] = "mut",
  [anon_sym_use] = "use",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_return] = "return",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_is] = "is",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_BANG] = "!",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_QMARK] = "\?",
  [anon_sym_PIPE] = "|",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON] = ":",
  [sym_source_file] = "source_file",
  [sym_attribute] = "attribute",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_keyword] = "keyword",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_percentage] = sym_percentage,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_component] = anon_sym_component,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_extension] = anon_sym_extension,
  [anon_sym_recipe] = anon_sym_recipe,
  [anon_sym_state] = anon_sym_state,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_source_file] = sym_source_file,
  [sym_attribute] = sym_attribute,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_keyword] = sym_keyword,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_percentage] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_component] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extension] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_recipe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_state] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 38,
        '"', 11,
        '&', 3,
        '(', 43,
        ')', 44,
        '*', 36,
        '+', 34,
        ',', 49,
        '-', 35,
        '.', 50,
        '/', 37,
        ':', 51,
        '<', 39,
        '=', 33,
        '>', 40,
        '?', 41,
        '@', 10,
        '[', 47,
        '\\', 5,
        ']', 48,
        '{', 45,
        '|', 42,
        '}', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(9);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '"', 16,
        '0', 16,
        '\\', 16,
        'n', 16,
        'r', 16,
        't', 16,
        '{', 16,
        '}', 16,
      );
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 38,
        '"', 11,
        '&', 3,
        '(', 43,
        ')', 44,
        '*', 36,
        '+', 34,
        ',', 49,
        '-', 35,
        '.', 50,
        '/', 37,
        ':', 51,
        '<', 39,
        '=', 33,
        '>', 40,
        '?', 41,
        '@', 10,
        '[', 47,
        ']', 48,
        '{', 45,
        '|', 42,
        '}', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_percentage);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(24);
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(32);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'c', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'l', 6,
        'm', 7,
        'n', 8,
        'r', 9,
        's', 10,
        't', 11,
        'u', 12,
        'w', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(17);
      if (lookahead == 'x') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 'n') ADVANCE(23);
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(34);
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(44);
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(51);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 37:
      if (lookahead == 'm') ADVANCE(54);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(59);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 50:
      if (lookahead == 'k') ADVANCE(63);
      END_STATE();
    case 51:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 55:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 58:
      if (lookahead == 'p') ADVANCE(68);
      END_STATE();
    case 59:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 64:
      if (lookahead == 'n') ADVANCE(72);
      END_STATE();
    case 65:
      if (lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 69:
      if (lookahead == 'n') ADVANCE(76);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_state);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 73:
      if (lookahead == 'u') ADVANCE(78);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(79);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_recipe);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 77:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 79:
      if (lookahead == 'o') ADVANCE(82);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 82:
      if (lookahead == 'n') ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_component);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_extension);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_percentage] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_component] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_extension] = ACTIONS(1),
    [anon_sym_recipe] = ACTIONS(1),
    [anon_sym_state] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym_attribute] = STATE(2),
    [sym_string] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_operator] = STATE(2),
    [sym_punctuation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_percentage] = ACTIONS(13),
    [sym_number] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_null] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(17),
    [anon_sym_component] = ACTIONS(17),
    [anon_sym_enum] = ACTIONS(17),
    [anon_sym_extension] = ACTIONS(17),
    [anon_sym_recipe] = ACTIONS(17),
    [anon_sym_state] = ACTIONS(17),
    [anon_sym_let] = ACTIONS(17),
    [anon_sym_mut] = ACTIONS(17),
    [anon_sym_use] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(17),
    [anon_sym_while] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(17),
    [anon_sym_in] = ACTIONS(17),
    [anon_sym_return] = ACTIONS(17),
    [anon_sym_break] = ACTIONS(17),
    [anon_sym_continue] = ACTIONS(17),
    [anon_sym_is] = ACTIONS(17),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_EQ_GT] = ACTIONS(19),
    [anon_sym_PLUS_EQ] = ACTIONS(19),
    [anon_sym_DASH_EQ] = ACTIONS(19),
    [anon_sym_STAR_EQ] = ACTIONS(19),
    [anon_sym_SLASH_EQ] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(19),
    [anon_sym_GT_EQ] = ACTIONS(19),
    [anon_sym_AMP_AMP] = ACTIONS(19),
    [anon_sym_PIPE_PIPE] = ACTIONS(19),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_QMARK] = ACTIONS(19),
    [anon_sym_PIPE] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym_attribute] = STATE(3),
    [sym_string] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_percentage] = ACTIONS(29),
    [sym_number] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_null] = ACTIONS(27),
    [anon_sym_fn] = ACTIONS(17),
    [anon_sym_component] = ACTIONS(17),
    [anon_sym_enum] = ACTIONS(17),
    [anon_sym_extension] = ACTIONS(17),
    [anon_sym_recipe] = ACTIONS(17),
    [anon_sym_state] = ACTIONS(17),
    [anon_sym_let] = ACTIONS(17),
    [anon_sym_mut] = ACTIONS(17),
    [anon_sym_use] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(17),
    [anon_sym_while] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(17),
    [anon_sym_in] = ACTIONS(17),
    [anon_sym_return] = ACTIONS(17),
    [anon_sym_break] = ACTIONS(17),
    [anon_sym_continue] = ACTIONS(17),
    [anon_sym_is] = ACTIONS(17),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_EQ_GT] = ACTIONS(19),
    [anon_sym_PLUS_EQ] = ACTIONS(19),
    [anon_sym_DASH_EQ] = ACTIONS(19),
    [anon_sym_STAR_EQ] = ACTIONS(19),
    [anon_sym_SLASH_EQ] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(19),
    [anon_sym_GT_EQ] = ACTIONS(19),
    [anon_sym_AMP_AMP] = ACTIONS(19),
    [anon_sym_PIPE_PIPE] = ACTIONS(19),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_QMARK] = ACTIONS(19),
    [anon_sym_PIPE] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_attribute] = STATE(3),
    [sym_string] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_identifier] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(36),
    [anon_sym_DQUOTE] = ACTIONS(39),
    [sym_percentage] = ACTIONS(42),
    [sym_number] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(45),
    [anon_sym_false] = ACTIONS(45),
    [sym_null] = ACTIONS(33),
    [anon_sym_fn] = ACTIONS(48),
    [anon_sym_component] = ACTIONS(48),
    [anon_sym_enum] = ACTIONS(48),
    [anon_sym_extension] = ACTIONS(48),
    [anon_sym_recipe] = ACTIONS(48),
    [anon_sym_state] = ACTIONS(48),
    [anon_sym_let] = ACTIONS(48),
    [anon_sym_mut] = ACTIONS(48),
    [anon_sym_use] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_else] = ACTIONS(48),
    [anon_sym_while] = ACTIONS(48),
    [anon_sym_for] = ACTIONS(48),
    [anon_sym_in] = ACTIONS(48),
    [anon_sym_return] = ACTIONS(48),
    [anon_sym_break] = ACTIONS(48),
    [anon_sym_continue] = ACTIONS(48),
    [anon_sym_is] = ACTIONS(48),
    [anon_sym_DASH_GT] = ACTIONS(51),
    [anon_sym_EQ_GT] = ACTIONS(51),
    [anon_sym_PLUS_EQ] = ACTIONS(51),
    [anon_sym_DASH_EQ] = ACTIONS(51),
    [anon_sym_STAR_EQ] = ACTIONS(51),
    [anon_sym_SLASH_EQ] = ACTIONS(51),
    [anon_sym_EQ_EQ] = ACTIONS(51),
    [anon_sym_BANG_EQ] = ACTIONS(51),
    [anon_sym_LT_EQ] = ACTIONS(51),
    [anon_sym_GT_EQ] = ACTIONS(51),
    [anon_sym_AMP_AMP] = ACTIONS(51),
    [anon_sym_PIPE_PIPE] = ACTIONS(51),
    [anon_sym_EQ] = ACTIONS(54),
    [anon_sym_PLUS] = ACTIONS(54),
    [anon_sym_DASH] = ACTIONS(54),
    [anon_sym_STAR] = ACTIONS(54),
    [anon_sym_SLASH] = ACTIONS(54),
    [anon_sym_BANG] = ACTIONS(54),
    [anon_sym_LT] = ACTIONS(54),
    [anon_sym_GT] = ACTIONS(54),
    [anon_sym_QMARK] = ACTIONS(51),
    [anon_sym_PIPE] = ACTIONS(54),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_RBRACK] = ACTIONS(57),
    [anon_sym_COMMA] = ACTIONS(57),
    [anon_sym_DOT] = ACTIONS(57),
    [anon_sym_COLON] = ACTIONS(57),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(60),
    [sym_identifier] = ACTIONS(62),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(60),
    [anon_sym_DQUOTE] = ACTIONS(60),
    [sym_percentage] = ACTIONS(60),
    [sym_number] = ACTIONS(62),
    [anon_sym_true] = ACTIONS(62),
    [anon_sym_false] = ACTIONS(62),
    [sym_null] = ACTIONS(62),
    [anon_sym_fn] = ACTIONS(62),
    [anon_sym_component] = ACTIONS(62),
    [anon_sym_enum] = ACTIONS(62),
    [anon_sym_extension] = ACTIONS(62),
    [anon_sym_recipe] = ACTIONS(62),
    [anon_sym_state] = ACTIONS(62),
    [anon_sym_let] = ACTIONS(62),
    [anon_sym_mut] = ACTIONS(62),
    [anon_sym_use] = ACTIONS(62),
    [anon_sym_if] = ACTIONS(62),
    [anon_sym_else] = ACTIONS(62),
    [anon_sym_while] = ACTIONS(62),
    [anon_sym_for] = ACTIONS(62),
    [anon_sym_in] = ACTIONS(62),
    [anon_sym_return] = ACTIONS(62),
    [anon_sym_break] = ACTIONS(62),
    [anon_sym_continue] = ACTIONS(62),
    [anon_sym_is] = ACTIONS(62),
    [anon_sym_DASH_GT] = ACTIONS(60),
    [anon_sym_EQ_GT] = ACTIONS(60),
    [anon_sym_PLUS_EQ] = ACTIONS(60),
    [anon_sym_DASH_EQ] = ACTIONS(60),
    [anon_sym_STAR_EQ] = ACTIONS(60),
    [anon_sym_SLASH_EQ] = ACTIONS(60),
    [anon_sym_EQ_EQ] = ACTIONS(60),
    [anon_sym_BANG_EQ] = ACTIONS(60),
    [anon_sym_LT_EQ] = ACTIONS(60),
    [anon_sym_GT_EQ] = ACTIONS(60),
    [anon_sym_AMP_AMP] = ACTIONS(60),
    [anon_sym_PIPE_PIPE] = ACTIONS(60),
    [anon_sym_EQ] = ACTIONS(62),
    [anon_sym_PLUS] = ACTIONS(62),
    [anon_sym_DASH] = ACTIONS(62),
    [anon_sym_STAR] = ACTIONS(62),
    [anon_sym_SLASH] = ACTIONS(62),
    [anon_sym_BANG] = ACTIONS(62),
    [anon_sym_LT] = ACTIONS(62),
    [anon_sym_GT] = ACTIONS(62),
    [anon_sym_QMARK] = ACTIONS(60),
    [anon_sym_PIPE] = ACTIONS(62),
    [anon_sym_LPAREN] = ACTIONS(60),
    [anon_sym_RPAREN] = ACTIONS(60),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(60),
    [anon_sym_LBRACK] = ACTIONS(60),
    [anon_sym_RBRACK] = ACTIONS(60),
    [anon_sym_COMMA] = ACTIONS(60),
    [anon_sym_DOT] = ACTIONS(60),
    [anon_sym_COLON] = ACTIONS(60),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_identifier] = ACTIONS(66),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(64),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [sym_percentage] = ACTIONS(64),
    [sym_number] = ACTIONS(66),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_null] = ACTIONS(66),
    [anon_sym_fn] = ACTIONS(66),
    [anon_sym_component] = ACTIONS(66),
    [anon_sym_enum] = ACTIONS(66),
    [anon_sym_extension] = ACTIONS(66),
    [anon_sym_recipe] = ACTIONS(66),
    [anon_sym_state] = ACTIONS(66),
    [anon_sym_let] = ACTIONS(66),
    [anon_sym_mut] = ACTIONS(66),
    [anon_sym_use] = ACTIONS(66),
    [anon_sym_if] = ACTIONS(66),
    [anon_sym_else] = ACTIONS(66),
    [anon_sym_while] = ACTIONS(66),
    [anon_sym_for] = ACTIONS(66),
    [anon_sym_in] = ACTIONS(66),
    [anon_sym_return] = ACTIONS(66),
    [anon_sym_break] = ACTIONS(66),
    [anon_sym_continue] = ACTIONS(66),
    [anon_sym_is] = ACTIONS(66),
    [anon_sym_DASH_GT] = ACTIONS(64),
    [anon_sym_EQ_GT] = ACTIONS(64),
    [anon_sym_PLUS_EQ] = ACTIONS(64),
    [anon_sym_DASH_EQ] = ACTIONS(64),
    [anon_sym_STAR_EQ] = ACTIONS(64),
    [anon_sym_SLASH_EQ] = ACTIONS(64),
    [anon_sym_EQ_EQ] = ACTIONS(64),
    [anon_sym_BANG_EQ] = ACTIONS(64),
    [anon_sym_LT_EQ] = ACTIONS(64),
    [anon_sym_GT_EQ] = ACTIONS(64),
    [anon_sym_AMP_AMP] = ACTIONS(64),
    [anon_sym_PIPE_PIPE] = ACTIONS(64),
    [anon_sym_EQ] = ACTIONS(66),
    [anon_sym_PLUS] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_STAR] = ACTIONS(66),
    [anon_sym_SLASH] = ACTIONS(66),
    [anon_sym_BANG] = ACTIONS(66),
    [anon_sym_LT] = ACTIONS(66),
    [anon_sym_GT] = ACTIONS(66),
    [anon_sym_QMARK] = ACTIONS(64),
    [anon_sym_PIPE] = ACTIONS(66),
    [anon_sym_LPAREN] = ACTIONS(64),
    [anon_sym_RPAREN] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(64),
    [anon_sym_RBRACE] = ACTIONS(64),
    [anon_sym_LBRACK] = ACTIONS(64),
    [anon_sym_RBRACK] = ACTIONS(64),
    [anon_sym_COMMA] = ACTIONS(64),
    [anon_sym_DOT] = ACTIONS(64),
    [anon_sym_COLON] = ACTIONS(64),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(68),
    [sym_identifier] = ACTIONS(70),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(68),
    [anon_sym_DQUOTE] = ACTIONS(68),
    [sym_percentage] = ACTIONS(68),
    [sym_number] = ACTIONS(70),
    [anon_sym_true] = ACTIONS(70),
    [anon_sym_false] = ACTIONS(70),
    [sym_null] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(70),
    [anon_sym_component] = ACTIONS(70),
    [anon_sym_enum] = ACTIONS(70),
    [anon_sym_extension] = ACTIONS(70),
    [anon_sym_recipe] = ACTIONS(70),
    [anon_sym_state] = ACTIONS(70),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_mut] = ACTIONS(70),
    [anon_sym_use] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(70),
    [anon_sym_else] = ACTIONS(70),
    [anon_sym_while] = ACTIONS(70),
    [anon_sym_for] = ACTIONS(70),
    [anon_sym_in] = ACTIONS(70),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_break] = ACTIONS(70),
    [anon_sym_continue] = ACTIONS(70),
    [anon_sym_is] = ACTIONS(70),
    [anon_sym_DASH_GT] = ACTIONS(68),
    [anon_sym_EQ_GT] = ACTIONS(68),
    [anon_sym_PLUS_EQ] = ACTIONS(68),
    [anon_sym_DASH_EQ] = ACTIONS(68),
    [anon_sym_STAR_EQ] = ACTIONS(68),
    [anon_sym_SLASH_EQ] = ACTIONS(68),
    [anon_sym_EQ_EQ] = ACTIONS(68),
    [anon_sym_BANG_EQ] = ACTIONS(68),
    [anon_sym_LT_EQ] = ACTIONS(68),
    [anon_sym_GT_EQ] = ACTIONS(68),
    [anon_sym_AMP_AMP] = ACTIONS(68),
    [anon_sym_PIPE_PIPE] = ACTIONS(68),
    [anon_sym_EQ] = ACTIONS(70),
    [anon_sym_PLUS] = ACTIONS(70),
    [anon_sym_DASH] = ACTIONS(70),
    [anon_sym_STAR] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(70),
    [anon_sym_BANG] = ACTIONS(70),
    [anon_sym_LT] = ACTIONS(70),
    [anon_sym_GT] = ACTIONS(70),
    [anon_sym_QMARK] = ACTIONS(68),
    [anon_sym_PIPE] = ACTIONS(70),
    [anon_sym_LPAREN] = ACTIONS(68),
    [anon_sym_RPAREN] = ACTIONS(68),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_RBRACE] = ACTIONS(68),
    [anon_sym_LBRACK] = ACTIONS(68),
    [anon_sym_RBRACK] = ACTIONS(68),
    [anon_sym_COMMA] = ACTIONS(68),
    [anon_sym_DOT] = ACTIONS(68),
    [anon_sym_COLON] = ACTIONS(68),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(72),
    [sym_identifier] = ACTIONS(74),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(72),
    [anon_sym_DQUOTE] = ACTIONS(72),
    [sym_percentage] = ACTIONS(72),
    [sym_number] = ACTIONS(74),
    [anon_sym_true] = ACTIONS(74),
    [anon_sym_false] = ACTIONS(74),
    [sym_null] = ACTIONS(74),
    [anon_sym_fn] = ACTIONS(74),
    [anon_sym_component] = ACTIONS(74),
    [anon_sym_enum] = ACTIONS(74),
    [anon_sym_extension] = ACTIONS(74),
    [anon_sym_recipe] = ACTIONS(74),
    [anon_sym_state] = ACTIONS(74),
    [anon_sym_let] = ACTIONS(74),
    [anon_sym_mut] = ACTIONS(74),
    [anon_sym_use] = ACTIONS(74),
    [anon_sym_if] = ACTIONS(74),
    [anon_sym_else] = ACTIONS(74),
    [anon_sym_while] = ACTIONS(74),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_in] = ACTIONS(74),
    [anon_sym_return] = ACTIONS(74),
    [anon_sym_break] = ACTIONS(74),
    [anon_sym_continue] = ACTIONS(74),
    [anon_sym_is] = ACTIONS(74),
    [anon_sym_DASH_GT] = ACTIONS(72),
    [anon_sym_EQ_GT] = ACTIONS(72),
    [anon_sym_PLUS_EQ] = ACTIONS(72),
    [anon_sym_DASH_EQ] = ACTIONS(72),
    [anon_sym_STAR_EQ] = ACTIONS(72),
    [anon_sym_SLASH_EQ] = ACTIONS(72),
    [anon_sym_EQ_EQ] = ACTIONS(72),
    [anon_sym_BANG_EQ] = ACTIONS(72),
    [anon_sym_LT_EQ] = ACTIONS(72),
    [anon_sym_GT_EQ] = ACTIONS(72),
    [anon_sym_AMP_AMP] = ACTIONS(72),
    [anon_sym_PIPE_PIPE] = ACTIONS(72),
    [anon_sym_EQ] = ACTIONS(74),
    [anon_sym_PLUS] = ACTIONS(74),
    [anon_sym_DASH] = ACTIONS(74),
    [anon_sym_STAR] = ACTIONS(74),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_BANG] = ACTIONS(74),
    [anon_sym_LT] = ACTIONS(74),
    [anon_sym_GT] = ACTIONS(74),
    [anon_sym_QMARK] = ACTIONS(72),
    [anon_sym_PIPE] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(72),
    [anon_sym_RPAREN] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(72),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_RBRACK] = ACTIONS(72),
    [anon_sym_COMMA] = ACTIONS(72),
    [anon_sym_DOT] = ACTIONS(72),
    [anon_sym_COLON] = ACTIONS(72),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(76),
    [sym_identifier] = ACTIONS(78),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(76),
    [anon_sym_DQUOTE] = ACTIONS(76),
    [sym_percentage] = ACTIONS(76),
    [sym_number] = ACTIONS(78),
    [anon_sym_true] = ACTIONS(78),
    [anon_sym_false] = ACTIONS(78),
    [sym_null] = ACTIONS(78),
    [anon_sym_fn] = ACTIONS(78),
    [anon_sym_component] = ACTIONS(78),
    [anon_sym_enum] = ACTIONS(78),
    [anon_sym_extension] = ACTIONS(78),
    [anon_sym_recipe] = ACTIONS(78),
    [anon_sym_state] = ACTIONS(78),
    [anon_sym_let] = ACTIONS(78),
    [anon_sym_mut] = ACTIONS(78),
    [anon_sym_use] = ACTIONS(78),
    [anon_sym_if] = ACTIONS(78),
    [anon_sym_else] = ACTIONS(78),
    [anon_sym_while] = ACTIONS(78),
    [anon_sym_for] = ACTIONS(78),
    [anon_sym_in] = ACTIONS(78),
    [anon_sym_return] = ACTIONS(78),
    [anon_sym_break] = ACTIONS(78),
    [anon_sym_continue] = ACTIONS(78),
    [anon_sym_is] = ACTIONS(78),
    [anon_sym_DASH_GT] = ACTIONS(76),
    [anon_sym_EQ_GT] = ACTIONS(76),
    [anon_sym_PLUS_EQ] = ACTIONS(76),
    [anon_sym_DASH_EQ] = ACTIONS(76),
    [anon_sym_STAR_EQ] = ACTIONS(76),
    [anon_sym_SLASH_EQ] = ACTIONS(76),
    [anon_sym_EQ_EQ] = ACTIONS(76),
    [anon_sym_BANG_EQ] = ACTIONS(76),
    [anon_sym_LT_EQ] = ACTIONS(76),
    [anon_sym_GT_EQ] = ACTIONS(76),
    [anon_sym_AMP_AMP] = ACTIONS(76),
    [anon_sym_PIPE_PIPE] = ACTIONS(76),
    [anon_sym_EQ] = ACTIONS(78),
    [anon_sym_PLUS] = ACTIONS(78),
    [anon_sym_DASH] = ACTIONS(78),
    [anon_sym_STAR] = ACTIONS(78),
    [anon_sym_SLASH] = ACTIONS(78),
    [anon_sym_BANG] = ACTIONS(78),
    [anon_sym_LT] = ACTIONS(78),
    [anon_sym_GT] = ACTIONS(78),
    [anon_sym_QMARK] = ACTIONS(76),
    [anon_sym_PIPE] = ACTIONS(78),
    [anon_sym_LPAREN] = ACTIONS(76),
    [anon_sym_RPAREN] = ACTIONS(76),
    [anon_sym_LBRACE] = ACTIONS(76),
    [anon_sym_RBRACE] = ACTIONS(76),
    [anon_sym_LBRACK] = ACTIONS(76),
    [anon_sym_RBRACK] = ACTIONS(76),
    [anon_sym_COMMA] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(76),
    [anon_sym_COLON] = ACTIONS(76),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(80),
    [sym_identifier] = ACTIONS(82),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(80),
    [anon_sym_DQUOTE] = ACTIONS(80),
    [sym_percentage] = ACTIONS(80),
    [sym_number] = ACTIONS(82),
    [anon_sym_true] = ACTIONS(82),
    [anon_sym_false] = ACTIONS(82),
    [sym_null] = ACTIONS(82),
    [anon_sym_fn] = ACTIONS(82),
    [anon_sym_component] = ACTIONS(82),
    [anon_sym_enum] = ACTIONS(82),
    [anon_sym_extension] = ACTIONS(82),
    [anon_sym_recipe] = ACTIONS(82),
    [anon_sym_state] = ACTIONS(82),
    [anon_sym_let] = ACTIONS(82),
    [anon_sym_mut] = ACTIONS(82),
    [anon_sym_use] = ACTIONS(82),
    [anon_sym_if] = ACTIONS(82),
    [anon_sym_else] = ACTIONS(82),
    [anon_sym_while] = ACTIONS(82),
    [anon_sym_for] = ACTIONS(82),
    [anon_sym_in] = ACTIONS(82),
    [anon_sym_return] = ACTIONS(82),
    [anon_sym_break] = ACTIONS(82),
    [anon_sym_continue] = ACTIONS(82),
    [anon_sym_is] = ACTIONS(82),
    [anon_sym_DASH_GT] = ACTIONS(80),
    [anon_sym_EQ_GT] = ACTIONS(80),
    [anon_sym_PLUS_EQ] = ACTIONS(80),
    [anon_sym_DASH_EQ] = ACTIONS(80),
    [anon_sym_STAR_EQ] = ACTIONS(80),
    [anon_sym_SLASH_EQ] = ACTIONS(80),
    [anon_sym_EQ_EQ] = ACTIONS(80),
    [anon_sym_BANG_EQ] = ACTIONS(80),
    [anon_sym_LT_EQ] = ACTIONS(80),
    [anon_sym_GT_EQ] = ACTIONS(80),
    [anon_sym_AMP_AMP] = ACTIONS(80),
    [anon_sym_PIPE_PIPE] = ACTIONS(80),
    [anon_sym_EQ] = ACTIONS(82),
    [anon_sym_PLUS] = ACTIONS(82),
    [anon_sym_DASH] = ACTIONS(82),
    [anon_sym_STAR] = ACTIONS(82),
    [anon_sym_SLASH] = ACTIONS(82),
    [anon_sym_BANG] = ACTIONS(82),
    [anon_sym_LT] = ACTIONS(82),
    [anon_sym_GT] = ACTIONS(82),
    [anon_sym_QMARK] = ACTIONS(80),
    [anon_sym_PIPE] = ACTIONS(82),
    [anon_sym_LPAREN] = ACTIONS(80),
    [anon_sym_RPAREN] = ACTIONS(80),
    [anon_sym_LBRACE] = ACTIONS(80),
    [anon_sym_RBRACE] = ACTIONS(80),
    [anon_sym_LBRACK] = ACTIONS(80),
    [anon_sym_RBRACK] = ACTIONS(80),
    [anon_sym_COMMA] = ACTIONS(80),
    [anon_sym_DOT] = ACTIONS(80),
    [anon_sym_COLON] = ACTIONS(80),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(84),
    [sym_identifier] = ACTIONS(86),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(84),
    [anon_sym_DQUOTE] = ACTIONS(84),
    [sym_percentage] = ACTIONS(84),
    [sym_number] = ACTIONS(86),
    [anon_sym_true] = ACTIONS(86),
    [anon_sym_false] = ACTIONS(86),
    [sym_null] = ACTIONS(86),
    [anon_sym_fn] = ACTIONS(86),
    [anon_sym_component] = ACTIONS(86),
    [anon_sym_enum] = ACTIONS(86),
    [anon_sym_extension] = ACTIONS(86),
    [anon_sym_recipe] = ACTIONS(86),
    [anon_sym_state] = ACTIONS(86),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_mut] = ACTIONS(86),
    [anon_sym_use] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(86),
    [anon_sym_else] = ACTIONS(86),
    [anon_sym_while] = ACTIONS(86),
    [anon_sym_for] = ACTIONS(86),
    [anon_sym_in] = ACTIONS(86),
    [anon_sym_return] = ACTIONS(86),
    [anon_sym_break] = ACTIONS(86),
    [anon_sym_continue] = ACTIONS(86),
    [anon_sym_is] = ACTIONS(86),
    [anon_sym_DASH_GT] = ACTIONS(84),
    [anon_sym_EQ_GT] = ACTIONS(84),
    [anon_sym_PLUS_EQ] = ACTIONS(84),
    [anon_sym_DASH_EQ] = ACTIONS(84),
    [anon_sym_STAR_EQ] = ACTIONS(84),
    [anon_sym_SLASH_EQ] = ACTIONS(84),
    [anon_sym_EQ_EQ] = ACTIONS(84),
    [anon_sym_BANG_EQ] = ACTIONS(84),
    [anon_sym_LT_EQ] = ACTIONS(84),
    [anon_sym_GT_EQ] = ACTIONS(84),
    [anon_sym_AMP_AMP] = ACTIONS(84),
    [anon_sym_PIPE_PIPE] = ACTIONS(84),
    [anon_sym_EQ] = ACTIONS(86),
    [anon_sym_PLUS] = ACTIONS(86),
    [anon_sym_DASH] = ACTIONS(86),
    [anon_sym_STAR] = ACTIONS(86),
    [anon_sym_SLASH] = ACTIONS(86),
    [anon_sym_BANG] = ACTIONS(86),
    [anon_sym_LT] = ACTIONS(86),
    [anon_sym_GT] = ACTIONS(86),
    [anon_sym_QMARK] = ACTIONS(84),
    [anon_sym_PIPE] = ACTIONS(86),
    [anon_sym_LPAREN] = ACTIONS(84),
    [anon_sym_RPAREN] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(84),
    [anon_sym_RBRACE] = ACTIONS(84),
    [anon_sym_LBRACK] = ACTIONS(84),
    [anon_sym_RBRACK] = ACTIONS(84),
    [anon_sym_COMMA] = ACTIONS(84),
    [anon_sym_DOT] = ACTIONS(84),
    [anon_sym_COLON] = ACTIONS(84),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(88), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_DQUOTE,
    ACTIONS(92), 1,
      sym_string_content,
    ACTIONS(94), 1,
      sym_escape_sequence,
    STATE(12), 1,
      aux_sym_string_repeat1,
  [16] = 5,
    ACTIONS(88), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_DQUOTE,
    ACTIONS(98), 1,
      sym_string_content,
    ACTIONS(100), 1,
      sym_escape_sequence,
    STATE(13), 1,
      aux_sym_string_repeat1,
  [32] = 5,
    ACTIONS(88), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_DQUOTE,
    ACTIONS(104), 1,
      sym_string_content,
    ACTIONS(107), 1,
      sym_escape_sequence,
    STATE(13), 1,
      aux_sym_string_repeat1,
  [48] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym_identifier,
  [55] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 16,
  [SMALL_STATE(13)] = 32,
  [SMALL_STATE(14)] = 48,
  [SMALL_STATE(15)] = 55,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punctuation, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punctuation, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 2, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 2, 0, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [112] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kome(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
